name: TEST deploy in ECR

on:
  workflow_dispatch:

jobs:
  build_and_push_ECR:
    runs-on: ubuntu-latest
    env:
      name: ${GITHUB_REPOSITORY#*/}"-dev"
      tag: ${GITHUB_SHA}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ECR_CLUSTER: ${{ vars.AWS_ECR_CLUSTER }}
      AWS_ECR_TASK_TEST: ${{ vars.AWS_ECR_TASK_TEST }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build docker image
        run: |
          docker build . -t ${{ env.ECR_REGISTRY }}/${{ env.name }}:${{ env.tag }}
          docker tag ${{ env.ECR_REGISTRY }}/${{ env.name }}:${{ env.tag }} ${{ env.ECR_REGISTRY }}/${{ env.name }}:latest

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image to ECR
        run: |
          docker push ${{ env.ECR_REGISTRY }}/${{ env.name }}:${{ env.tag }}
          docker push ${{ env.ECR_REGISTRY }}/${{ env.name }}:latest

      - name: Update ECS service
        run: |
          aws ecs update-service \
          --cluster ${{ env.AWS_ECR_CLUSTER }} \
          --service ${{ env.AWS_ECR_TASK_TEST }} \
          --force-new-deployment
