name: TEST public

on:
  workflow_dispatch:

jobs:
  build_and_push_ECR:
    runs-on: ubuntu-latest
    env:
      name: ${GITHUB_REPOSITORY#*/}"-dev"
      tag: ${GITHUB_SHA}
      ECR_REGISTRY: ${{ secrets.TEST_ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        env:
          REGISTRY: i6t0p5x2
          #REGISTRY_ALIAS: my-ecr-public-registry-alias
          REPOSITORY: r-dee_go_quorum
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t public.ecr.aws/i6t0p5x2/r-dee_go_quorum:$IMAGE_TAG .

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
            mask-password: 'true'
            registry-type: public

      - name: Push docker image to Amazon ECR Public
        env:
            REGISTRY: i6t0p5x2
            #REGISTRY_ALIAS: my-ecr-public-registry-alias
            REPOSITORY: r-dee_go_quorum
            IMAGE_TAG: ${{ github.sha }}
        run: |
            docker push public.ecr.aws/i6t0p5x2/r-dee_go_quorum:$IMAGE_TAG          