name: TEST public

on:
  workflow_dispatch:

jobs:
  build_and_push_ECR:
    runs-on: ubuntu-latest
    env:
      name: ${GITHUB_REPOSITORY#*/}"-dev"
      tag: ${GITHUB_SHA}
      ECR_REGISTRY: ${{ secrets.TEST_ECR_REGISTRY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v3
      #   with:
      #     aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}

      - name: Build docker image
        run: |
          docker build . -t ${{ env.ECR_REGISTRY }}:latest

      - name: Login to Public ECR
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws/i6t0p5x2/r-dee_go_quorum
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: Push Docker image to ECR
        run: |
          docker push ${{ env.ECR_REGISTRY }}:latest
