name: Test error action

on:
  workflow_dispatch:
  pull_request: 
  push:

jobs:
  build_and_push_ECR:
    runs-on: ubuntu-22.04
    steps:
      - name: step
        run: |
          rmdir qwerty
          exit 1


